# Generated by Django 5.1.6 on 2025-03-01 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 7, 5, 47, 485268)),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 7, 5, 47, 485268)),
        ),
    ]
